### ISSUE TITLE
Show list of online users?

### ISSUE THREAD

**Issue by Matthew2D** [RestingCoder/discord-widget#1]
Can you make it so it shows an actual list of online users?

Thanks.

**Comment by RestingCoder** [comment]
I sure could. How would you like to have them listed? Under the channels? Also, would you like to only show the users who are online but not in a voice channel there? I can add this tomorrow night most likely.

**Comment by Matthew2D** [comment]
Can it be at the bottom? Preferably a drop down; have it say "Online Users"?

BTW I love your widget! Much better than the official one; I hate branding. 

Im using it here http://thesgn.com/board/forums/. There is a discord tab next to teamspeak.

**Comment by RestingCoder** [comment]
Added. New parameter. showAllUsers: true/false
