### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by Xpectre** [RestingCoder/discord-widget#11]
Good afternoon,

First of all, thank you for your time developing this alternative widget. I found it on Google and I'm trying to use it, however, my server's link isn't working. I tried using the official widget and your alternative widget but it seems like it will never connect.

Here is the server link that you are using with your code snippet:

https://discordapp.com/widget?id=91990396455878656

And here is my server link

https://discordapp.com/widget?id=158115212174557185

As you can see my server is not connecting at all and I don't know what to do. I checked my website several times but I realized that it's not my problem. Do you have any idea? I posted on Reedit asking for help and also tried to contact you on that server that you used to show your work.

Thanks in advance for the help,

Fernando.

**Comment by RestingCoder** [comment]
If you have enabled the widget checkbox in the Server Settings within Discord, and it still isn't working, you may need to contact Discord directly for this one.
