### ISSUE TITLE
Enhancement - Color Customization

### ISSUE THREAD

**Issue by HandGrenade** [RestingCoder/discord-widget#13]
Hello!

Firstly, thank you for this amazing Discord Widget! 

Now to my enhancement. Would it be possible to add further configuration so we are able to set up custom colors for the widget? :)

Thanks!

**Comment by RestingCoder** [comment]
You can customize the styling/colors using standard CSS. For element ids or classes, just inspect them with your browser :)

**Comment by HandGrenade** [comment]
Thank you! :)
