### ISSUE TITLE
Script Link not enable

### ISSUE THREAD

**Issue by Ladylain** [RestingCoder/discord-widget#14]
I have an issue with this, 

this line,
`<script type="text/javascript" src="http://discord.deliriousdrunkards.com/discord.min.js"></script>`
does not function correctly ! 

is this normal ? 

Thx

**Comment by madl3ss87** [comment]
im getting the same issue

when ever u go to http://discord.deliriousdrunkards.com asks u to sign in.. looks like its been taken down

**Comment by RestingCoder** [comment]
This will be fixed this evening. Had some server issues with the provider. Too much usage. Won't happen again after this.

**Comment by RestingCoder** [comment]
Should be good to go now. Let me know if you see any issues.
