### ISSUE TITLE
Null Problem

### ISSUE THREAD

**Issue by joshuapatrickcarpenter** [RestingCoder/discord-widget#15]
Hello there, something isn't quite working correctly with your widget. I click the "Join Server" button and I think there is an error somewhere; it throws /null up in the url bar of the browser (actually does try to take you to a directory called null) and then on repeated clicks, it keeps stacking /null, so the address bar eventually looks like example.com/null/null/null/null you get the idea. Any thoughts as to what's happening? The widget box is checked in the Discord server settings.

**Comment by RestingCoder** [comment]
Link me to the page so I can check it out.

**Comment by joshuapatrickcarpenter** [comment]
Hey Josh, it requires a password to see, you can log in with my email
address (joshuapatrickcarpenter@gmail.com) and the password *test*

The site is http://www.thenexusgg.com

Thanks!

**Comment by LexiBelle** [comment]
Hey, I'm also having this null issue.

I have the widget on a test page atm: http://www.punchcraft.us/test

**Comment by RestingCoder** [comment]
Make sure you have an Instant Invite Channel set in the Widget section of the Server Settings screen within Discord.
