### ISSUE TITLE
Widget wont load due to TypeError

### ISSUE THREAD

**Issue by PRIZZA** [RestingCoder/discord-widget#16]
I've tried embedding this widget on my website, but it fails to load and the console reports the following error:
```
Uncaught TypeError: $ is not a function
d @ discord.min.js:1
discordWidget.render @ discord.min.js:1
(anonymous function) @ (index):675
```

**Comment by RestingCoder** [comment]
Please provide a link to the page so I can check it out.

**Comment by PRIZZA** [comment]
Sure thing! On the right-hand side, under the "Discord" section. - [https://aeonrivals.com](url)

**Comment by RestingCoder** [comment]
Sorry for the delay. I will be working on this today and tomorrow, so if you want to put it back on your site and send a link, please do.
