### ISSUE TITLE
Join Server button.

### ISSUE THREAD

**Issue by Frostwolf221** [RestingCoder/discord-widget#17]
Was just wondering if there was a way to make the join server button to open a new tab once clicked rather than open on the same tab.

**Comment by skyraiD-0** [comment]
join server link won't work on chrome or Edge, is anyway to fix it?

**Comment by RestingCoder** [comment]
Not currently. I plan on adding this tomorrow at some point.

Skyraid-0, I would need a link to the page to look at it.

**Comment by skyraiD-0** [comment]
Here is my test site, our main site ran the same software so we work on test site before we move any data or modifications.

http://skyraid.net/forums/

**Comment by skyraiD-0** [comment]
have you looked into the Join button issue?

**Comment by RestingCoder** [comment]
Sorry, I haven't gotten a chance yet. I broke my hand so it takes a lot for me to type currently. I will work on this again soon.

**Comment by RestingCoder** [comment]
Should be good to go now.

**Comment by skyraiD-0** [comment]
Thanks brah going to check it tonight. How's your hand ? Better now

**Comment by RestingCoder** [comment]
Not much better, but I didn't want to make you wait too long.

Let me know if you have any issues when you check it out later.

**Comment by skyraiD-0** [comment]
Definitely I will report it back

**Comment by skyraiD-0** [comment]
Josh you fixed it man. good work send me your email cuz i may have some beers here for ya.
