### ISSUE TITLE
Widget only showing in Chrome (no other browser)

### ISSUE THREAD

**Issue by originalsharp** [RestingCoder/discord-widget#21]
Hi,

Thanks for this awesome widget, the design is so customisable, much better than the official one!

I'm having trouble with it though. I'm using it on our enjin website as part of a new design. I noticed it displayed perfectly in Chrome (it's in the fourth tab of our multitab sidebar here: http://www.varshen.com/testsidebar) but it isn't showing in IE, Edge or Firefox.

At first I thought the issue might be that it wouldn't work as part of a multitab or nested sidebar, so I tested it as a stand-alone widget too, but same issue - it displays perfectly in Chrome, but will not show up in IE, Edge or Firefox.

Any assistance would be fantastic, hoping to introduce these new element throughout our website in the next day or two.

Thanks

**Comment by originalsharp** [comment]
Quick update - realised I was using a reeeeeally old version of the .js file, so I've downloaded and installed the latest .js version and it now works in Firefox and Edge also. Still not working in Internet Explorer and as a complete novice, I really can't think what else to check. Any advice at all on this would be most helpful. Thanks!

**Comment by RestingCoder** [comment]
I'll take a look tonight. Should work everywhere, but maybe something changed on the Discord side since I last worked on this.

**Comment by originalsharp** [comment]
Thank you, really appreciate it!

**Comment by originalsharp** [comment]
Hi, sorry for the multiple posts, just wondering if you'd managed to spot something that I didn't? Thanks for your help.

**Comment by RestingCoder** [comment]
Working on fixing this right now. IE doesn't support a part of JS I am using, surprisingly.

**Comment by RestingCoder** [comment]
Should be good to go now.
