### ISSUE TITLE
HTML/JS Version not loading

### ISSUE THREAD

**Issue by smeddly** [RestingCoder/discord-widget#23]
Hey there. I would like to start by saying thank you so much for the alternative widget it is great. I am having an issue getting the HTML/JS version to load on my test site. I have your iframe version loading just fine. To be honest it is better then the one from discord directly.
the JS version should be loading on the bottom of my widget test page here. Any Ideas?
http://junglegaming.comli.com/DiscordTest.html

**Comment by RestingCoder** [comment]
Forgot to edit the code snippet when I last updated it. Replace the script tag with this:

    <script type="text/javascript" src="http://discord.deliriousdrunkards.com/discord.js"></script>

instead of 

    <script type="text/javascript" src="discord.js"></script>
