### ISSUE TITLE
Join Server Not Working?

### ISSUE THREAD

**Issue by Luszis** [RestingCoder/discord-widget#24]
When users click the join server button they are taken to a blank page that says Cannot GET /null.
Is there a way to configure the link on that button?

**Comment by RestingCoder** [comment]
Be sure you have selected an Instant Invite Channel inside the Widget section of the Server Settings screen.

**Comment by Luszis** [comment]
You are awesome!! That did the trick, thank you!!

**Comment by RestingCoder** [comment]
Awesome :)
