### ISSUE TITLE
Background color of the "join server"

### ISSUE THREAD

**Issue by borgqueenx** [RestingCoder/discord-widget#25]
I disabled the css themes and tried to look for hints in the code for background-color and tried to add that manually. but i cant seem to change the blue background color of the "Join Server" link in this widget...

**Comment by lutechi** [comment]
For now I just override with "!importants".

Example:
```
.discord-join {
background-color: white !important;
}
.discord-join a {
color: red !important;
}
.discord-join:hover {
background-color: blue !important;
}
```
