### ISSUE TITLE
Blank, not loading

### ISSUE THREAD

**Issue by PaladinBrewer** [RestingCoder/discord-widget#26]
Hello, I have code like so:

```
`{source}
<script type="text/javascript" src="http://discord.deliriousdrunkards.com/discord.min.js"></script>
<script type="text/javascript">
discordWidget.init({
serverId: '208354495464341505',
title: 'Discord Widget Title',
join: true,
alphabetical: false,
theme: 'dark',
hideChannels: false,
showAllUsers: true,
allUsersDefaultState: true,
showNick: false
});
discordWidget.render();
</script>

<div class="discord-widget"></div>

{/source}`
```

The source encloser is for the Sourcer plugin so I can use javascript in a module. Anyway, the module is blank. It's at www.swordofthedragon.org, any thoughts? Do I have something wrong?

**Comment by randomtom** [comment]
I'm using Joomla and I'm kinda getting the same issue. I try to implement the iframe code but the box stays blank. The original discord widget works on the other hand. Don't know what I'm doing wrong.

Thanks in advance!

**Comment by RestingCoder** [comment]
Link me to the site. I'll try checking it out tomorrow before I go to work.

**Comment by randomtom** [comment]
https://pr-ksk.de/

Thanks for the reply :)
The modul is on the left side right beneath the "Mumble Channel Viewer"

**Comment by randomtom** [comment]
I just found out what I was missing. The code doesn't work when the website is running SSL. That's a shame.

**Comment by RestingCoder** [comment]
I'll see what I can do about that tomorrow morning. Sorry!

**Comment by PaladinBrewer** [comment]
Ah sorry didn't know there were responses. I've changed my Joomla 
template so if you looked it might not have shown up. It is there now 
though:

http://swordofthedragon.org/

I'm trying to use the javascript, not a big fan of iframe. It's blank, I 
don't know if that's an issue on your end it I'm not calling the 
javascript correctly through the module.

**Comment by RestingCoder** [comment]
Got called into work early but I'll check it out on my day off tomorrow (Monday).

**Comment by randomtomx** [comment]
don't worry. I'm very glad you are willing to look into it :) Take your time!

**Comment by lutechi** [comment]
Having the same issue with iframe or js. My site is also https, not sure if that has anything to do with it.

Thanks again.

**Comment by RestingCoder** [comment]
Yeah, it is because I don't serve the widget with SSL. I'm working on it. Some weird family stuff came up that has been taking up my free time but I'm hoping to get a chance to finish either tonight or tomorrow. Really sorry guys.

**Comment by jimmy2x2x** [comment]
If you could be so kind as to look at mine please - sorry the code is so messy, half way through a revamp.
get this message when trying to connect. "Cannot GET /null"

http://www.theoldguard.co.uk/devindex.html

Many thanks

**Comment by RestingCoder** [comment]
@jimmy2x2x That sounds like you don't have the widget enabled in the Server Settings on Discord.

**Comment by RestingCoder** [comment]
For everyone else, I am working on getting the js hosted in a way that will allow you to use https. It may be a couple days.

**Comment by RestingCoder** [comment]
Everyone try the new JS/HTML code snippet [here](discord.deliriousdrunkards.com).

This should work properly. If not, let me know!

**Comment by PaladinBrewer** [comment]
I don't think this link is working?

**Comment by PaladinBrewer** [comment]
Nevermind I found the code.

So here's the weird issue. It shows up fine on my forum page:
http://swordofthedragon.org/guild-forums

But any other page it does not. Any thoughts on why that would be? On 
the other pages I see a console error:
discord-widget.min.js:1 Uncaught TypeError: Cannot read property 
'append' of null.

**Comment by lutechi** [comment]
Thanks is working perfectly.
