### ISSUE TITLE
Still not loading

### ISSUE THREAD

**Issue by PaladinBrewer** [RestingCoder/discord-widget#28]
Hello, you closed my ticket though it still does not work on my page. I asked a couple people to take a look, and they both said the same thing: 

> We use jQuery no conflict mode for all our JS so I don't think its a template issue. I do see that Discord isn't using it as its calling $("head") instead of jQuery("head"). This might be causing the issue but you'd have to check with Discord author.

> as issue with discord because native http://swordofthedragon.org/media/jui/js/jquery-noconflict.js is loaded, but this discord script doesn't respect the global namespace and assumes that $ is taken by jQuery only.It's better to contact discord authors and ask them to correct their code, it should use jQuery but not $

Any help on this? Site is swordofthedragon.org

**Comment by PaladinBrewer** [comment]
Actually I fixed this myself. I took your javascript and moved it locally so I could edit. I replaced all "$" with "jQuery" and now it is working.

**Comment by Arty2** [comment]
Indeed it is not working on WordPress. Could you please also list the options from http://discord.deliriousdrunkards.com/ on GitHub's readme?
