### ISSUE TITLE
User online list breaks widget

### ISSUE THREAD

**Issue by Matthew2D** [RestingCoder/discord-widget#3]
I overwrote all files for the widget and added the showallusers line in the javascript. Here is what happens.

![image](http://i.imgur.com/ou8VXh6.png)

Here is the code.

```javascript
<script type="text/javascript" src="/board/js/SGNWidgets/sgnDiscord/discord.min.js"></script>
<script type="text/javascript">
  discordWidget.init({
    serverId: '123456789',
    join: false,
    alphabetical: false,
    theme: 'dark',
    showAllUsers: true
  });
  discordWidget.render();
</script>

<div class="discord-widget"></div>
```

If I remove the showallusers line it everything works (except showing all users ofcourse)

**Comment by Matthew2D** [comment]
....

I didn't put it the server ID. Sorry!

**Comment by RestingCoder** [comment]
No problem! Glad it works now!
