### ISSUE TITLE
Unable to use custom css

### ISSUE THREAD

**Issue by Yohrn** [RestingCoder/discord-widget#32]
Hello ;)

First, thank you for your widget.
When i paste the iframe code, it's ok on my website (test website) : testares2.hajiro.fr.
When i try to use your JS script, it doesn"t display anymore (only the widget title). Is there a problem with Wordpress or Joomla ?

My wish is to use custom css. With iframe, css custom does not work at all, that's why i tried the JS script code.

Thank you for your support !

**Comment by thezoid** [comment]
if this is still happening, please let me know what it says in your browser console.

**Comment by RestingCoder** [comment]
As there has been no response, I am closing this issue. Please open a new one if you are still having trouble.
