### ISSUE TITLE
Pagespeed Error

### ISSUE THREAD

**Issue by kcmartz** [RestingCoder/discord-widget#34]
Trying to optimize my site as much as possible, and by switching to this widget vs Discord's own, I was able to make it go from a D rank to an A rank, but there's still more I could do to improve it. I'm erroring out on **Leverage Browser Caching** from this widget.

It is saying the dark.min.css has no expiration date specified, as well as the discord.min.js (same no expiration). Don't know if 'discordapp.com/api/servers/XXX/embed.json' is used by you (removed my server ID) or not, but it's also throwing that error.

As to the Defer parsing of JS, I can probably fix that with a plugin to my website (on discord.min.js).

Also saying that `http://discordi.deliriousdrunkards.com/render?id=129835479855136768&title=KVG%20Discord&theme=dark&join=true&abc=false&showall=false&toggle=false&shownick=false` has some inline JS which can be reduced to make everything faster.

Under Enable Gzip Compression, `dark.min.css and discord.min.js` can be compressed further in the production part of the widget with a 73% and 65% reduction, respectively. Minifying the JS and CSS could really help with first-time visitor's impressions of each person who uses this widget, and their viewers may be on mobile.

`http://discordi.deliriousdrunkards.com/render?id=129835479855136768&title=KVG%20Discord&theme=dark&join=true&abc=false&showall=false&toggle=false&shownick=false`'s HTML could also be reduced to save another 3%.

> The following publicly cacheable, compressible resources should have a "Vary: Accept-Encoding" header:
> http://discord.deliriousdrunkards.com/dark.min.css
> http://discord.deliriousdrunkards.com/discord.min.js

Other than these, you have the perfect light-weight discord widget to put on other's websites. Whatever you can do on your end, I'd be greatly appreciative, and whatever's up to me, let me know.

**Comment by RestingCoder** [comment]
There isn't much I can do to help with this, unfortunately.
