### ISSUE TITLE
List gets too long very fast, which pushes join button too far down.

### ISSUE THREAD

**Issue by AskAlice** [RestingCoder/discord-widget#35]
I am writing the website for a community with a discord server that has >1300 members. This server is used mostly for chat, but voice is used for developers and the few users who choose to join voice chat. The most important info people may need is not whether or not there are people in the voice chat, but rather whether or not people of certain ranks are online. Is this possible with the discord api? I looked through the json but it seems pretty bare in terms of user info.

Listing all users (regardless of rank) requires me to put a max-height on the element, but then the join server button gets scrollbarred. At least if possible add an option to move join server to top.

If it could list the online users by rank like it does in the sidebar of any text channel, that would be amazing.
Thanks.

**Comment by apexmage** [comment]
+1 to moving the join server button to the top. I have the same issue where I have many users online so I have to limit the height of the container and that forces the join button down below.

**Comment by celkie** [comment]
+1 for listing by rank. It would be helpful for the users of my community to be able to see if there are administrators online!  For the meantime I have put max-height and overflow CSS on the ul.discord-tree, as then the button will not be scrollbarred, only the user list. :)

**Comment by RestingCoder** [comment]
I'll add an option to have the Join button at the top shortly. Sorry about not responding previously.

**Comment by RogueStryder** [comment]
Hi there,
Is there a way to add a scrolling feature to the ppl online?

**Comment by Antes** [comment]
Try the following @RogueStryder 

```
.discord-allusers {
	max-height: 250px;
	overflow-y: scroll;
	overflow-x: hidden;
}
```
