### ISSUE TITLE
Join button links to null

### ISSUE THREAD

**Issue by SatsumaBenji** [RestingCoder/discord-widget#40]
Using the discord-widget, embedded into iframe on webpage.
The join button anchor references "http://discordi.deliriousdrunkards.com/null" and doesn't join the server.

**Comment by savmctavish** [comment]
Have the same issue.
I have this running on our clan website and i get this result "[http://veteranelite.enjin.com/null](url)"
Can you advise as to setting the Join button to reference my Discord?

Peace out :-)

**Comment by RestingCoder** [comment]
Make sure instant invite is enabled in the widget section of the server settings.
