### ISSUE TITLE
Self Hosting Issue/Guide

### ISSUE THREAD

**Issue by Yoobo** [RestingCoder/discord-widget#45]
Hi, love your work, very cool.

I'm having some issues trying to work out how to self host the widget. The embedded and the iframe.

For the iframe to work, (js isn't my strongest) it looks like it builds the html page as needed. This is my iframe code currently(sanitized), similar with your example:

`<iframe src="//myWebsiteURL/discord/discord-iframe-server/discord-iframe-server.js/render?id=123456789&theme=dark&join=false&abc=false&showall=true&toggle=true&shownick=false" width="300px" height="400px" frameborder="0"></iframe>`

Is this the correct way to use the iframe code? I noticed there's also cdn calls in that js file, I'd like to totally self host this too and help with what to change would be appreciated.

Could you please detail how this is possible.

**Comment by RestingCoder** [comment]
The iframe version can't really be self hosted because it is hitting a nodes server to render the widget.

To self host the js version you can just download the files from here, then change any references to other files within the code to fit your server. So instead of the CDN URLs, replace them with your own.

**Comment by Yoobo** [comment]
Thank you for the prompt reply!

No worries, that makes sense re the iframe. As a stop gap I just made my own html doc with the embedded code and loaded that in. Works fine so far.

For others who come across this, you'll need to create the folder for variable 'a' in the js file or remove it. Find: `+a+` in discord-widget.min.js.

All I need to do is adjust the iframe so that the height is automatic, quite fidgety. But that isn't a problem for here imo.

Thanks again!
