### ISSUE TITLE
https

### ISSUE THREAD

**Issue by Infinito47** [RestingCoder/discord-widget#46]
I am experiencing issues with your plugin on my website due to your website only allowing http://. Can you enable https please?

**Comment by RestingCoder** [comment]
Use the new CDN URL, and it should work with HTTPS.

**Comment by Nefiji** [comment]
New CDN URL?

**Comment by Nefiji** [comment]
Can I use the iframe with the new CDN URL?

**Comment by RestingCoder** [comment]
Unfortunately, no.
