### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by shadowdragon64** [RestingCoder/discord-widget#48]
I do not know how to use the id or how to work it. If you could leave a page help button or a little comment letting us know how to use it like where to paste it how to paste it and etc

**Comment by Antes** [comment]
You can find your server-id via discord's website (Far more easily) once you connect your server it shows something like the following which contains the serverID twice copy one and use it on snip.

`https://discordapp.com/channels/107362567793422336/107362567793422336`
