### ISSUE TITLE
discord-widget with Wordpress plugin "Jetpack"

### ISSUE THREAD

**Issue by ThxAndBye** [RestingCoder/discord-widget#5]
Hey,

i have a rather specific problem with the widget.
It works absolutely fine, but causes issues with other javascript / ajax on my Wordpress site.
When the widget is active, my infinite scroll doesn't work anymore.
Im using the infinite scroll from the "Jetpack by WordPress.com" plugin.

Is there a way to load the widget without it interfering with other code?
Would it be possible, that there will we a wordpress plugin version of your widget?

regards

**Comment by RestingCoder** [comment]
Link me to a page where I can see this, and I will look into it.

**Comment by ThxAndBye** [comment]
This is my site I'd like to use it on:
-> http://shin-sekai.de/

Page 2 also exists but since im using infinite scroll, there are no buttons on the bottom.
-> http://shin-sekai.de/page/2/

**Comment by RestingCoder** [comment]
Looking over it, I am not seeing anything that would cause this. I tried a few things, but nothing seemed to fix it.

Unless you can see any errors within the Admin section of Wordpress, there is not much I can do. I will look into setting up a test install on WordPress to see if I can either fix it or create a plugin instead. Without knowing what is causing the issue within WordPress, it is hard to say whether a plugin would even work to get around this.

Sorry about that. I'll let you know when I have the time to look into this. It would most likely be after the holidays.

**Comment by ThxAndBye** [comment]
Awesome, thanks for looking into it. Im not in a hurry so everything you do is appreciated a lot and i will integrate it, if the problem is solved.
Is it okay for you, if i take it of the site, so the scrolling works again, or do you still need it for testing?

It might solve the problem if the widget would use the intergrated jQuery from Wordpress (thats why I think a wordpress plugin can solve this) , but since im not very skilled at js or jQuery, that might not be the case.

**Comment by RestingCoder** [comment]
You can take it off your site, and I'll setup a Wordpress install of my own.

One of the things I tried was only using the jQuery you already had on the site, but it didn't fix it. I'll figure it out.

**Comment by RestingCoder** [comment]
Give the iframe version a try, and let me know if you still run into trouble!

http://discord.deliriousdrunkards.com/
