### ISSUE TITLE
Someone has stolen your code.

### ISSUE THREAD

**Issue by bentenz5** [RestingCoder/discord-widget#50]
Hi there, I wanted to let you know that a user by the name of CikerDeveloper, who has previously stolen code from myself and others, has stolen your code.

He goes by 1microfix on Discord and some other places on the internet.

I would personally advise submitting a DMCA request and keeping an eye on the profile to ensure your code isnt stolen again.

Here's the link to the repo which he stole your code, he didnt realize the bug report button still links here.

https://github.com/CikerDeveloper/Discord-Widget

And his profile link: 

https://github.com/CikerDeveloper

**Comment by RestingCoder** [comment]
Thank you <3

**Comment by bentenz5** [comment]
Np.
