### ISSUE TITLE
Option to strip out avatar images

### ISSUE THREAD

**Issue by capalex65** [RestingCoder/discord-widget#53]
The normal Discord widget loads in 128x128 images, but displays them as 16x16. Not sure if this does as well, but... This means there's a lot of wasted data being transferred. So, is it possible to add in an option that strips images out of the widget completely?

**Comment by continuumfall** [comment]
You can add ?size=16 to the end of the avatar url to get the 16x16 image. Should probably get added to the js file by default. I'm using ?size=32 and styled it like the discord app sidebar hehe
![screen shot 2018-02-20 at 18 52 54](https://user-images.githubusercontent.com/20994642/36442998-765a9656-166f-11e8-96fd-da10ce9b7a81.png)
