### ISSUE TITLE
Adjust width and height?

### ISSUE THREAD

**Issue by ngx3** [RestingCoder/discord-widget#6]
Thanks for the work done. Is there a way to adjust the width and height? it doesn't show online users, it's set to "true".

**Comment by RestingCoder** [comment]
I wouldn't recommend changing the height at all, as it gets taller to fit the content, and you'd end up cutting parts off in some cases.

To adjust the width, you can use CSS on the .discord-widget element.

If you have access to the CSS for your site, you can do that like this:

    .discord-widget { width: 200px; }

If you don't have access to the CSS directly, you can replace the last line of the embed code provided with:

    <div class="discord-widget" style="width: 200px;"></div>

**Comment by ngx3** [comment]
Thanks! Any chance of putting a scroll on the widget so it doesn't get longer? We have lots of users coming on there + plus channels to be added.



Online users works now.

**Comment by RestingCoder** [comment]
You can do that with this CSS:

    height: 200px;
    overflow-y: auto;

This will set the height, and if it gets taller than that, it will add a scrollbar.

**Comment by ngx3** [comment]
I randomly started working and auto ressized (width) itself.

**Comment by RestingCoder** [comment]
You don't have to download anything. If you are still having trouble, link me to the page so I can see it, and describe the issue you are having in detail.

**Comment by ngx3** [comment]
Well I created a css file on my forum board with
[code].discord-widget { width: 250px; }
	height: 150px;
        overflow-y: auto;[/code]

But it didn't change the appearance the second time I edited the css only the first time, is there some sort of delay perhaps? As soon as I deleted the css it reverts back to it's original state, it won't allow me to edit the height only width.

**Comment by RestingCoder** [comment]
.discord-widget { 
        width: 250px;
        height: 150px;
        overflow-y: auto;
    }
