### ISSUE TITLE
problem on free phpbb forum "xooit" with chat connexion + discord widget

### ISSUE THREAD

**Issue by yotitchy** [RestingCoder/discord-widget#7]
Hi !

i recently found your script, who is better than just using default iframe from discord ! :)

but when i use the script the chat of my forum dont work, it's just disconnected and impossible de log in. :/ when i delete the script it work again :/

with script : http://rebellion.xooit.org/index.php?theme=test
without script : http://rebellion.xooit.org/index.php

yes i've modified some things, i know nothing about scripts, but i understand things i see
like here : http://the-unknowns.eu/index.php/BoardList/
but even if i delete this the problem is the same :/

so i added :

.discord-widget {background-color: #e8f4fc;}
.discord-widget .discord-join {background-color: #444444!important;}
.discord-widget .discord-title {display: none;}
.discord-tree {font-size: 80% !important;max-height: 400px;overflow: auto;}
.discord-tree ul, .discord-tree li {margin-left: 5px !important;}
.discord-widget .discord-user span {color: #5e5e5e;opacity: 1;}
.discord-widget .discord-user {color: #0b4d90;}
.discord-widget .discord-channel {color: #0b4d90;padding-bottom: 2px !important;padding-top: 6px !important;}

and paste your script :

<script type="text/javascript" src="http://discord.deliriousdrunkards.com/discord.min.js"></script>
<script type="text/javascript">
  discordWidget.init({
    serverId: '108199400509038592',
    title: 'Discord',
    join: true,
    alphabetical: false,
    theme: 'none',
    hideChannels: ['Channel Name 1', 'Channel Name 2'],
    showAllUsers: true,
    allUsersDefaultState: true
  });
  discordWidget.render();
</script>

Have an idea ?
its a crappy free forum, i can only edit templates in admin menu of the forum.

**Comment by RestingCoder** [comment]
Sorry you are having trouble with this. I have setup a test forum on that service, and was able to reproduce the issue. Unfortunately, there isn't really anything I can do to fix it, as their options are very limited.

**Comment by RestingCoder** [comment]
I'll be working on an iframe style solution in the next few days. That should work for you. I'll let you know when it is ready.

**Comment by yotitchy** [comment]
ho nice thanks ! :)

**Comment by RestingCoder** [comment]
Sorry for the delay with this. I finally found the time to work on this, and it should be done in the next two days. Thanks for your patience!

**Comment by yotitchy** [comment]
no problem ! thanks for solving this in anyway you can :)
i wish it will help some other users ^^

**Comment by RestingCoder** [comment]
iframe tab here:

http://discord.deliriousdrunkards.com/
