### ISSUE TITLE
Discord widget tab?

### ISSUE THREAD

**Issue by inputuserhere** [RestingCoder/discord-widget#9]
Hi,

Just had a quick question. How would I add discord to my website/forum side tab? When you click on it, it pops out and you can scroll, connect..

Like this 
![2013-09-09_2119](https://cloud.githubusercontent.com/assets/16825276/12493573/91bdc59a-c053-11e5-9c76-71c934e52810.png)

**Comment by RestingCoder** [comment]
In general, this is beyond the scope of the widget itself. This can be done using standard HTML, CSS, and some JS to control the popping in and out.
